export const IconBar = () => import(/* webpackChunkName: "views/menus/IconBar" */ './IconBar.vue')
export const MenuIcon = () => import(/* webpackChunkName: "views/menus/MenuIcon" */ './MenuIcon.vue')
export const Accordion = () => import(/* webpackChunkName: "views/menus/Accordion" */ './Accordion.vue')
export const Tabs = () => import(/* webpackChunkName: "views/menus/Tabs" */ './Tabs.vue')
export const VerticalTabs = () => import(/* webpackChunkName: "views/menus/VerticalTabs" */ './VerticalTabs.vue')
export const TabHeaders = () => import(/* webpackChunkName: "views/menus/TabHeaders" */ './TabHeaders.vue')
export const TopNavigation = () => import(/* webpackChunkName: "views/menus/TopNavigation" */ './TopNavigation.vue')
export const ResponsiveTopnav = () => import(/* webpackChunkName: "views/menus/ResponsiveTopnav" */ './ResponsiveTopnav.vue')
export const SideNavigation = () => import(/* webpackChunkName: "views/menus/SideNavigation" */ './SideNavigation.vue')
export const FullscreenNavigation = () => import(/* webpackChunkName: "views/menus/FullscreenNavigation" */ './FullscreenNavigation.vue')
export const OffCanvasMenu = { page: () => import(/* webpackChunkName: "views/menus/OffCanvasMenu" */ './OffCanvasMenu.vue'), menu: 'Off-Cavnas Menu' }
export const HoverableSidenav = { page: () => import(/* webpackChunkName: "views/menus/HoverableSidenav" */ './HoverableSidenav.vue'), menu: 'Hover Sidenav Buttons' }
export const HorizontalScrollMenu = () => import(/* webpackChunkName: "views/menus/HorizontalScrollMenu" */ './HorizontalScrollMenu.vue')
export const VerticalMenu = () => import(/* webpackChunkName: "views/menus/VerticalMenu" */ './VerticalMenu.vue')
export const BottomNavigation = () => import(/* webpackChunkName: "views/menus/BottomNavigation" */ './BottomNavigation.vue')
export const ResponsiveBottomNavigation = { page: () => import(/* webpackChunkName: "views/menus/ResponsiveBottomNavigation" */ './ResponsiveBottomNavigation.vue'), menu: 'Responsive Bottom Nav' }
export const BottomBorderNavLinks = () => import(/* webpackChunkName: "views/menus/BottomBorderNavLinks" */ './BottomBorderNavLinks.vue')
export const FixedMenu = () => import(/* webpackChunkName: "views/menus/FixedMenu" */ './FixedMenu.vue')
export const SlideDownBarOnScroll = () => import(/* webpackChunkName: "views/menus/SlideDownBarOnScroll" */ './SlideDownBarOnScroll.vue')
export const StickyNavbar = () => import(/* webpackChunkName: "views/menus/StickyNavbar" */ './StickyNavbar.vue')
export const HoverableDropdown = () => import(/* webpackChunkName: "views/menus/HoverableDropdown" */ './HoverableDropdown.vue')
export const ClickableDropdown = () => import(/* webpackChunkName: "views/menus/ClickableDropdown" */ './ClickableDropdown.vue')
export const DropdownNavbar = () => import(/* webpackChunkName: "views/menus/DropdownNavbar" */ './DropdownNavbar.vue')
export const MegaMenu = () => import(/* webpackChunkName: "views/menus/MegaMenu" */ './MegaMenu.vue')
export const Pagination = () => import(/* webpackChunkName: "views/menus/Pagination" */ './Pagination.vue')
export const Breadcrumbs = () => import(/* webpackChunkName: "views/menus/Breadcrumbs" */ './Breadcrumbs.vue')
export const ButtonGroup = () => import(/* webpackChunkName: "views/menus/ButtonGroup" */ './ButtonGroup.vue')
export const VerticalButtonGroup = () => import(/* webpackChunkName: "views/menus/VerticalButtonGroup" */ './VerticalButtonGroup.vue')
